### ISSUE TITLE
Trying to compile demo throws errors on unknown symbols for arm64

### ISSUE THREAD

**Issue by teuteuguy** [aws/amazon-freertos-ble-ios-sdk#25]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_AWSServiceConfiguration", referenced from:
      objc-class-ref in AmazonFreeRTOSDevice.o
  "_OBJC_CLASS_$_AWSEndpoint", referenced from:
      objc-class-ref in AmazonFreeRTOSDevice.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I suspect this is a Mac M1 problem.
Can this be ported to Mac please, ASAP ?

Also, the project has so many warnings on AWS/Amazon libraries. Is that normal ?

Trying to build with Xcode 12.5
